# Generated by Django 5.0.6 on 2024-06-25 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.customer')),
            ],
        ),
    ]
