# Generated by Django 5.0.6 on 2024-06-29 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_admin_work_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_work_create',
            name='category',
            field=models.CharField(choices=[('two wheeler with gear', 'two wheeler with gear'), ('two wheeler without gear', 'two wheeler without gear'), ('three wheeler', 'three wheeler'), ('four wheeler', 'four wheeler')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admin_work_create',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin_work_create',
            name='vehicle_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin_work_create',
            name='worksmanager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.worksmanager'),
            preserve_default=False,
        ),
    ]
