# Generated by Django 5.0.6 on 2024-06-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_alter_admin_work_create_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_work_create',
            name='category',
            field=models.CharField(blank=True, choices=[('two wheeler with gear', 'two wheeler with gear'), ('two wheeler without gear', 'two wheeler without gear'), ('three wheeler', 'three wheeler'), ('four wheeler', 'four wheeler')], max_length=50, null=True),
        ),
    ]
