# Generated by Django 5.0.6 on 2024-07-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_alter_admin_work_create_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_work_create',
            name='status',
            field=models.CharField(blank=True, choices=[('repairing', 'repairing'), ('repairing done', 'repairing done'), ('released', 'released')], default='Pending', max_length=100, null=True),
        ),
    ]
