# Generated by Django 5.0.6 on 2024-07-04 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0007_alter_admin_work_create_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_date', models.CharField(max_length=6)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.admin_work_create')),
            ],
        ),
    ]
