# Generated by Django 5.0.6 on 2024-07-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_customerpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='card_number',
            field=models.IntegerField(max_length=16),
        ),
    ]
