# Generated by Django 5.0.6 on 2024-07-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0011_alter_customerpayment_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_work_create',
            name='pay',
            field=models.IntegerField(default=0),
        ),
    ]
